export enum ActionType {
  // user actions
  LOGIN_USER = "LOGIN_USER",
  REGISTER_USER = "REGISTER_USER",
  LOGOUT_USER = "LOGOUT_USER",
  // jobs actions
  FETCHING_JOBS = "FETCHING_JOBS",
  CREATING_JOB = "CREATING_JOB",
  DELETING_JOB = "DELETING_JOB",
  // current job actions
  GET_CURRENT_JOB = "GET_CURRENT_JOB",
  // candidates actions
  FETCHING_CANDIDATES = "FETCHING_CANDIDATES",
  CREATING_CANDIDATE = "CREATING_CANDIDATE",
  DELETING_CANDIDATE = "DELETING_CANDIDATE",
  // current candidate
  GET_CURRENT_CANDIDATE = "GET_CURRENT_CANDIDATE",
}
